/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "api_constants.h"

namespace api {

const apiConstants g_api_constants;

apiConstants::apiConstants() {
}

} // namespace

