/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef api_CONSTANTS_H
#define api_CONSTANTS_H

#include "api_types.h"

namespace api {

class apiConstants {
 public:
  apiConstants();

};

extern const apiConstants g_api_constants;

} // namespace

#endif
