/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef general_CONSTANTS_H
#define general_CONSTANTS_H

#include "general_types.h"

namespace general {

class generalConstants {
 public:
  generalConstants();

};

extern const generalConstants g_general_constants;

} // namespace

#endif
