/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "general_constants.h"

namespace general {

const generalConstants g_general_constants;

generalConstants::generalConstants() {
}

} // namespace

